name: Use GitHub Secret
on:
  push:
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Secret Value
        run: echo "Using the secret safely!"
        env:
          SECRET: ${{ secrets.SECRET }}
